openapi: 3.0.0
info:
  title: API IA
  version: 1.0.0
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X - API-KEY
paths:
  /api/emotion_detection:
    post:
      summary: Endpoint pour la détection des émotions humaines dans une image
      security:
      - ApiKeyAuth: []
      - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application / json:
            schema:
              type: object
              properties:
                image:
                  type: base64 encoded image
      responses:
        '200':
          description: Succès
          content:
            application / json:
              schema:
                type: object
                properties:
                  emotion:
                    type: string
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
