openapi: 3.0.0
info:
  title: API IA
  version: 1.0.0
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /auth/token
          scopes:
            read: Lecture
            write: Écriture
paths:
  /api/api:
    post:
      summary: 'API principale (mode: fast/safe)'
      security:
      - ApiKeyAuth: []
      - OAuth2:
        - read
        - write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                user_id:
                  type: integer
                mode:
                  type: string
                  enum:
                  - fast
                  - safe
            examples:
              example:
                value:
                  data: test
                  user_id: 1
                  mode: fast
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  details:
                    type: object
              examples:
                example:
                  value:
                    result: ok
                    details:
                      info: détail
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
