openapi: 3.0.0
info:
  title: API IA
  version: 1.0.0
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /auth/token
          scopes:
            read: Lecture
            write: Écriture
paths:
  /api/memory:
    post:
      summary: Stockage clé/valeur
      security:
      - ApiKeyAuth: []
      - OAuth2:
        - read
        - write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                value:
                  type: string
            examples:
              example:
                value:
                  key: foo
                  value: bar
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
              examples:
                example:
                  value:
                    status: ok
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
        '404':
          description: Not Found
