openapi: 3.0.0
info:
  title: API IA
  version: 1.0.0
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /auth/token
          scopes:
            read: Lecture
            write: Écriture
paths:
  /api/tts:
    post:
      summary: 'Synthèse vocale (lang: fr/en)'
      security:
      - ApiKeyAuth: []
      - OAuth2:
        - read
        - write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                lang:
                  type: string
                  enum:
                  - fr
                  - en
            examples:
              example:
                value:
                  text: Bonjour
                  lang: fr
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  audio:
                    type: string
              examples:
                example:
                  value:
                    audio: base64...
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
        '422':
          description: Unprocessable Entity
