site_name: Athalia Pipeline IA
site_description: Documentation technique et utilisateur du générateur IA souverain
site_author: Arkalia
repo_url: https://github.com/arkalia/athalia-pipeline
theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: cyan
nav:
  - Accueil: index.md
  - Architecture: architecture.md
  - Utilisation: utilisation.md
  - Modules:
      - Génération: generation.md
      - Nettoyage: cleanup.md
      - CI/CD: ci.md
      - Dashboard: dashboard.md
      - Onboarding: onboarding.md
      - Sécurité: security.md
  - Tests: tests.md
  - Automatisation: automatisation.md
  - FAQ: faq.md
  - Changelog: changelog.md
  - Industrialisation & Confiance: industrialisation.md
