sequenceDiagram
    participant User
    participant API
    API->>module_1: Appel /api/module_1
    module_1-->>API: Réponse
    API->>module_2: Appel /api/module_2
    module_2-->>API: Réponse
    API->>module_3: Appel /api/module_3
    module_3-->>API: Réponse
    API->>module_4: Appel /api/module_4
    module_4-->>API: Réponse
    API->>module_5: Appel /api/module_5
    module_5-->>API: Réponse
    API->>module_6: Appel /api/module_6
    module_6-->>API: Réponse
    API->>module_7: Appel /api/module_7
    module_7-->>API: Réponse
    API->>module_8: Appel /api/module_8
    module_8-->>API: Réponse
    API->>module_9: Appel /api/module_9
    module_9-->>API: Réponse
    API->>module_10: Appel /api/module_10
    module_10-->>API: Réponse
    API->>module_11: Appel /api/module_11
    module_11-->>API: Réponse
    API->>module_12: Appel /api/module_12
    module_12-->>API: Réponse
    API->>module_13: Appel /api/module_13
    module_13-->>API: Réponse
    API->>module_14: Appel /api/module_14
    module_14-->>API: Réponse
    API->>module_15: Appel /api/module_15
    module_15-->>API: Réponse
    API->>module_16: Appel /api/module_16
    module_16-->>API: Réponse
    API->>module_17: Appel /api/module_17
    module_17-->>API: Réponse
    API->>module_18: Appel /api/module_18
    module_18-->>API: Réponse
    API->>module_19: Appel /api/module_19
    module_19-->>API: Réponse
    API->>module_20: Appel /api/module_20
    module_20-->>API: Réponse
    API->>module_21: Appel /api/module_21
    module_21-->>API: Réponse
    API->>module_22: Appel /api/module_22
    module_22-->>API: Réponse
    API->>module_23: Appel /api/module_23
    module_23-->>API: Réponse
    API->>module_24: Appel /api/module_24
    module_24-->>API: Réponse
    API->>module_25: Appel /api/module_25
    module_25-->>API: Réponse
    API->>module_26: Appel /api/module_26
    module_26-->>API: Réponse
    API->>module_27: Appel /api/module_27
    module_27-->>API: Réponse
    API->>module_28: Appel /api/module_28
    module_28-->>API: Réponse
    API->>module_29: Appel /api/module_29
    module_29-->>API: Réponse
    API->>module_30: Appel /api/module_30
    module_30-->>API: Réponse
    API->>module_31: Appel /api/module_31
    module_31-->>API: Réponse
    API->>module_32: Appel /api/module_32
    module_32-->>API: Réponse
    API->>module_33: Appel /api/module_33
    module_33-->>API: Réponse
    API->>module_34: Appel /api/module_34
    module_34-->>API: Réponse
    API->>module_35: Appel /api/module_35
    module_35-->>API: Réponse
    API->>module_36: Appel /api/module_36
    module_36-->>API: Réponse
    API->>module_37: Appel /api/module_37
    module_37-->>API: Réponse
    API->>module_38: Appel /api/module_38
    module_38-->>API: Réponse
    API->>module_39: Appel /api/module_39
    module_39-->>API: Réponse
    API->>module_40: Appel /api/module_40
    module_40-->>API: Réponse
    API->>module_41: Appel /api/module_41
    module_41-->>API: Réponse
    API->>module_42: Appel /api/module_42
    module_42-->>API: Réponse
    API->>module_43: Appel /api/module_43
    module_43-->>API: Réponse
    API->>module_44: Appel /api/module_44
    module_44-->>API: Réponse
    API->>module_45: Appel /api/module_45
    module_45-->>API: Réponse
    API->>module_46: Appel /api/module_46
    module_46-->>API: Réponse
    API->>module_47: Appel /api/module_47
    module_47-->>API: Réponse
    API->>module_48: Appel /api/module_48
    module_48-->>API: Réponse
    API->>module_49: Appel /api/module_49
    module_49-->>API: Réponse
    API->>module_50: Appel /api/module_50
    module_50-->>API: Réponse
    API->>module_51: Appel /api/module_51
    module_51-->>API: Réponse
    API->>module_52: Appel /api/module_52
    module_52-->>API: Réponse
    API->>module_53: Appel /api/module_53
    module_53-->>API: Réponse
    API->>module_54: Appel /api/module_54
    module_54-->>API: Réponse
    API->>module_55: Appel /api/module_55
    module_55-->>API: Réponse
    API->>module_56: Appel /api/module_56
    module_56-->>API: Réponse
    API->>module_57: Appel /api/module_57
    module_57-->>API: Réponse
    API->>module_58: Appel /api/module_58
    module_58-->>API: Réponse
    API->>module_59: Appel /api/module_59
    module_59-->>API: Réponse
    API->>module_60: Appel /api/module_60
    module_60-->>API: Réponse
    API->>module_61: Appel /api/module_61
    module_61-->>API: Réponse
    API->>module_62: Appel /api/module_62
    module_62-->>API: Réponse
    API->>module_63: Appel /api/module_63
    module_63-->>API: Réponse
    API->>module_64: Appel /api/module_64
    module_64-->>API: Réponse
    API->>module_65: Appel /api/module_65
    module_65-->>API: Réponse
    API->>module_66: Appel /api/module_66
    module_66-->>API: Réponse
    API->>module_67: Appel /api/module_67
    module_67-->>API: Réponse
    API->>module_68: Appel /api/module_68
    module_68-->>API: Réponse
    API->>module_69: Appel /api/module_69
    module_69-->>API: Réponse
    API->>module_70: Appel /api/module_70
    module_70-->>API: Réponse
    API->>module_71: Appel /api/module_71
    module_71-->>API: Réponse
    API->>module_72: Appel /api/module_72
    module_72-->>API: Réponse
    API->>module_73: Appel /api/module_73
    module_73-->>API: Réponse
    API->>module_74: Appel /api/module_74
    module_74-->>API: Réponse
    API->>module_75: Appel /api/module_75
    module_75-->>API: Réponse
    API->>module_76: Appel /api/module_76
    module_76-->>API: Réponse
    API->>module_77: Appel /api/module_77
    module_77-->>API: Réponse
    API->>module_78: Appel /api/module_78
    module_78-->>API: Réponse
    API->>module_79: Appel /api/module_79
    module_79-->>API: Réponse
    API->>module_80: Appel /api/module_80
    module_80-->>API: Réponse
    API->>module_81: Appel /api/module_81
    module_81-->>API: Réponse
    API->>module_82: Appel /api/module_82
    module_82-->>API: Réponse
    API->>module_83: Appel /api/module_83
    module_83-->>API: Réponse
    API->>module_84: Appel /api/module_84
    module_84-->>API: Réponse
    API->>module_85: Appel /api/module_85
    module_85-->>API: Réponse
    API->>module_86: Appel /api/module_86
    module_86-->>API: Réponse
    API->>module_87: Appel /api/module_87
    module_87-->>API: Réponse
    API->>module_88: Appel /api/module_88
    module_88-->>API: Réponse
    API->>module_89: Appel /api/module_89
    module_89-->>API: Réponse
    API->>module_90: Appel /api/module_90
    module_90-->>API: Réponse
    API->>module_91: Appel /api/module_91
    module_91-->>API: Réponse
    API->>module_92: Appel /api/module_92
    module_92-->>API: Réponse
    API->>module_93: Appel /api/module_93
    module_93-->>API: Réponse
    API->>module_94: Appel /api/module_94
    module_94-->>API: Réponse
    API->>module_95: Appel /api/module_95
    module_95-->>API: Réponse
    API->>module_96: Appel /api/module_96
    module_96-->>API: Réponse
    API->>module_97: Appel /api/module_97
    module_97-->>API: Réponse
    API->>module_98: Appel /api/module_98
    module_98-->>API: Réponse
    API->>module_99: Appel /api/module_99
    module_99-->>API: Réponse
    API->>module_100: Appel /api/module_100
    module_100-->>API: Réponse
    API->>module_101: Appel /api/module_101
    module_101-->>API: Réponse
    API->>module_102: Appel /api/module_102
    module_102-->>API: Réponse
    API->>module_103: Appel /api/module_103
    module_103-->>API: Réponse
    API->>module_104: Appel /api/module_104
    module_104-->>API: Réponse
    API->>module_105: Appel /api/module_105
    module_105-->>API: Réponse
    API->>module_106: Appel /api/module_106
    module_106-->>API: Réponse
    API->>module_107: Appel /api/module_107
    module_107-->>API: Réponse
    API->>module_108: Appel /api/module_108
    module_108-->>API: Réponse
    API->>module_109: Appel /api/module_109
    module_109-->>API: Réponse
    API->>module_110: Appel /api/module_110
    module_110-->>API: Réponse
    API->>module_111: Appel /api/module_111
    module_111-->>API: Réponse
    API->>module_112: Appel /api/module_112
    module_112-->>API: Réponse
    API->>module_113: Appel /api/module_113
    module_113-->>API: Réponse
    API->>module_114: Appel /api/module_114
    module_114-->>API: Réponse
    API->>module_115: Appel /api/module_115
    module_115-->>API: Réponse
    API->>module_116: Appel /api/module_116
    module_116-->>API: Réponse
    API->>module_117: Appel /api/module_117
    module_117-->>API: Réponse
    API->>module_118: Appel /api/module_118
    module_118-->>API: Réponse
    API->>module_119: Appel /api/module_119
    module_119-->>API: Réponse
    API->>module_120: Appel /api/module_120
    module_120-->>API: Réponse
    API-->>User: Résultat global
