# Alias Arkalia/Athalia Dev
alias ath-chat='continue'
alias ath-clean='find . -name "__pycache__" -o -name ".DS_Store" -o -name "*.log" -exec rm -rf {} +'
alias ath-dev-boost='bash $(dirname "$BASH_SOURCE")/ath-dev-boost.sh'
alias ath-perplex='open https://www.perplexity.ai/'
alias ath-test='task test'
alias ath-lint='task lint'
alias ath-build='task build'
alias ath-new='bash setup/ath-new.sh'
alias ath-smart='python3 $(dirname "$BASH_SOURCE")/../agents/ath_context_prompt.py'