# Configuration des chemins pour Athalia
paths:
  # Dossiers principaux
  root: "."
  core: "athalia_core"
  modules: "modules"
  plugins: "plugins"
  templates: "templates"
  prompts: "prompts"
  agents: "agents"
  
  # Dossiers de données et configuration
  data: "data"
  config: "config"
  logs: "logs"
  
  # Dossiers de projets et tests
  projects: "projects"
  tests: "tests"
  
  # Dossiers de documentation et dashboard
  docs: "docs"
  dashboard: "dashboard"
  
  # Dossiers de build et cache
  setup: "setup"
  tasks: "tasks"
  blueprints_history: "blueprints_history"
  
  # Fichiers de configuration
  config_files:
    main: "config/athalia_config.yaml"
    pytest: "config/pytest.ini"
    pyproject: "config/pyproject.toml"
    requirements: "config/requirements.txt"
    docker_compose: "config/docker-compose.yml"
  
  # Fichiers de données
  data_files:
    profils: "data/profils_utilisateur.db"
    analytics: "data/athalia_analytics.db"
    reports: "data/athalia_report_*.json"
  
  # Scripts principaux
  scripts:
    unified: "athalia_unified.py"
    enhanced: "athalia_unified_enhanced.py"
    quick_start: "athalia_quick_start.py"
    run_tests: "setup/run_tests.sh" 