# Configuration pre-commit pour Athalia
# Automatise les vérifications avant chaque commit

repos:
  # Hooks de base uniquement
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10240']
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: requirements-txt-fixer

# Configuration globale
default_language_version:
  python: python3
