version: '3'
tasks:
  build:
    desc: "Générer le projet IA (menu CLI)"
    cmds:
      - python3 -m athalia_core.main

  test:
    desc: "Lancer tous les tests unitaires et d’intégration"
    cmds:
      - pytest tests/

  lint:
    desc: "Lint du code Python (flake8)"
    cmds:
      - flake8 athalia_core/ tests/

  clean:
    desc: "Nettoyer tous les artefacts inutiles (caches, logs, pyc, etc.)"
    cmds:
      - find . -name "__pycache__" -o -name ".DS_Store" -o -name "*.log" -o -name "*.pyc" -o -name ".*" -exec rm -rf {} +

  export:
    desc: "Exporter le pipeline complet (tar.gz)"
    cmds:
      - python3 export_pipeline.py

  dashboard:
    desc: "Générer le dashboard global (HTML, Mermaid)"
    cmds:
      - python3 -m athalia_core.main

  audit:
    desc: "Audit sécurité sur tous les projets IA"
    cmds:
      - |
        for d in ia_project*; do
          if [ -d "$d" ]; then
            python3 -m athalia_core.main <<< $'6\n'$d'\n7\n'
          fi
        done 