services:
  reachy_2023:
    image: pollenrobotics/reachy_2023:1.1
    container_name: reachy_2023
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
    volumes:
      - ${PWD}:/opt/docker_reachy_2023_src:ro
    network_mode: "host"
    entrypoint: /package/start.sh