openapi: 3.0.0
info:
  title: API IA
  version: 1.0.0
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
paths:
  /api/detectWindDirection:
    post:
      summary: Détecte la direction du vent dans l'image fournie
      security:
      - ApiKeyAuth: []
      - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: image_path
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  direction:
                    type: string
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
