name: CI

on: [push, pull_request]

jobs:
  test:
    runs - on: ubuntu - latest
    steps:
      - uses: actions / checkout@v4
      - name: Set up Python
        uses: actions / setup-python@v4
        with:
          python - version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
      - name: Upload coverage report
        uses: actions / upload-artifact@v3
        with:
          name: coverage - report
          path: .coverage

  deploy:
    needs: test
    runs - on: ubuntu - latest
    if: github.event_name == "push" && github.ref == "refs / heads/main"
    steps:
      - uses: actions / checkout@v4
      - name: Set up Python
        uses: actions / setup-python@v4
        with:
          python - version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy
        run: |
          echo "Deploying to production..."
          # Add your deployment logic here
