info:
  description: Application web IA complète avec API REST FastAPI, authentification
    JWT, base de données PostgreSQL, tests unitaires et d'intégration, documentation
    Swagger, déploiement Docker, CI/CD GitHub Actions, monitoring Prometheus, et interface
    web React
  title: web
  version: 1.0.0
openapi: 3.0.0
paths:
  /:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                type: object
          description: Message de bienvenue
      summary: Point d'entrée
